package com.mcac.devices.enums


enum class ContactCardType {
    CONTACT_CARD_TYPE_A_CPU,
    CONTACT_CARD_TYPE_B_CPU,
    CONTACT_CARD_TYPE_4442,
    CONTACT_CARD_TYPE_4428,
    CONTACT_CARD_TYPE_AT24C02,
    CONTACT_CARD_TYPE_AT88SC102,
    CONTACT_CARD_TYPE_AT88SC1604,
    CONTACT_CARD_TYPE_AT88SC1608,
    CONTACT_CARD_TYPE_AT88SC153,
    CONTACT_CARD_TYPE_AT24C16,
    CONTACT_CARD_TYPE_MAX
}