package com.mcac.devices.enums

enum class ContactlessCardType {
    CONTACTLESS_CARD_TYPE_A_CPU,
    CONTACTLESS_CARD_TYPE_B_CPU,
    CONTACTLESS_CARD_TYPE_A_CLASSIC_MINI,
    CONTACTLESS_CARD_TYPE_A_CLASSIC_1K,
    CONTACTLESS_CARD_TYPE_A_CLASSIC_4K,
    CONTACTLESS_CARD_TYPE_A_UL_64,
    CONTACTLESS_CARD_TYPE_A_UL_192,
    CONTACTLESS_CARD_TYPE_A_MP_2K_SL1,
    CONTACTLESS_CARD_TYPE_A_MP_4K_SL1,
    CONTACTLESS_CARD_TYPE_A_MP_2K_SL2,
    CONTACTLESS_CARD_TYPE_A_MP_4K_SL2,
    CONTACTLESS_CARD_TYPE_NTAG_213,
    CONTACTLESS_CARD_TYPE_NTAG_215,
    CONTACTLESS_CARD_TYPE_NTAG_216,
    CONTACTLESS_CARD_TYPE_M0,
    CONTACTLESS_CARD_TYPE_FELICA,
}